name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # The branch to push from

jobs:
  build:
    name: Build Flutter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - run: flutter pub get
      - run: flutter build web --release --base-href /tz/

      - name: Archive production assets
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'build/web'

  deploy:
    name: Deploy to Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3